# Generated by Django 4.2.3 on 2024-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_alter_admissionstudent_admission_policy_agreement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionstudent',
            name='admission_policy_agreement',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='board',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='children_of_freedom_fighter',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='group',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='marksheet_image',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='ssc_registration',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='ssc_roll',
        ),
        migrations.RemoveField(
            model_name='admissionstudent',
            name='tribal_status',
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='children_name',
            field=models.TextField(blank=True, help_text='Na yacadra kece mai nai vola ni sucu kei na yabaki ra sucu kina', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='course_name',
            field=models.TextField(blank=True, help_text='Na vuli e qaravi tiko kei na yabaki me oti kina'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='date_married',
            field=models.DateField(blank=True, help_text='Na siga e vakamau kina - Dd/Mm/Yy eg 23/03/2010', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='date_papitaiso_kina',
            field=models.DateField(blank=True, help_text='Na tikini siga ka Papitaiso kina/ ke kilai ga na yabaki ia me vaka na 01/01/2002 e vakaraitaka ni yabaki 2002', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='date_sigadina_kina',
            field=models.DateField(blank=True, help_text='Na tikini siga ka Siga Dina kina/ ke kilai ga na yabaki ia me vaka na 01/01/2002 e vakaraitaka ni yabaki 2002', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='explaination_education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='highest_qualification',
            field=models.CharField(choices=[('PHD', 'Doctor'), ('MST', 'Masters'), ('DGR', 'Degree'), ('DIP', 'Diploma'), ('CER', 'Certificate'), ('F7', 'Form 7'), ('F6', 'Form 6'), ('OTH', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='koro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='nona_tabacakacaka',
            field=models.TextField(blank=True, help_text='Na nona i tukutuku ena vuku ni nona i tavi vakai Talatala'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='nona_tubu_ni_veiqaravi',
            field=models.TextField(blank=True, help_text='Nona record ni veiqaravi vakai wiliwili ni vavakoso'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='nona_tukutuku_ni_cakacaka',
            field=models.TextField(blank=True, help_text='Na nona i tukutuku ena vuku ni nona cakacaka'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='nona_tukutuku_tavi_vakai_talatala',
            field=models.TextField(blank=True, help_text='Na nona i tukutuku ena vuku ni nona i tavi vakai Talatala'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='nona_wasewase',
            field=models.TextField(blank=True, help_text='Na nona i tukutuku ena vuku ni nona i tavi vakai Talatala'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='other_qualification',
            field=models.TextField(blank=True, help_text='Na vuli tale eso e rawati kei na yabaki'),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='spouse_job',
            field=models.CharField(blank=True, help_text='Na nona cakacaka ko Watina', max_length=255),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='spouse_name',
            field=models.CharField(blank=True, help_text='Na yacana kece mai nai vola ni sucu', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='tavi_qaravi_nikua',
            field=models.CharField(blank=True, choices=[('talcg', 'Talatala Vakacegu'), ('tlqs', 'Talatala Qase'), ('talyc', 'Talatala Yaco'), ('taltv', 'Talatala Vakatovolei')], help_text='Nai tavi vakai talatala ka qarava tiko ena gauna nikua', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='tikina',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='vakamacala_tale_eso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='yabaki_tabaki_kina',
            field=models.DateField(blank=True, help_text='Na tikini siga ka Tabaki kina', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='yabaki_tekivu_kina',
            field=models.CharField(blank=True, help_text='Na yabaki ka tekivu kacivi kina me qarava nai tavi vakai Talatala ka taura tiko nikua', max_length=255),
        ),
        migrations.AddField(
            model_name='admissionstudent',
            name='yasana',
            field=models.CharField(blank=True, choices=[('ba', 'Ba'), ('bua', 'Bua'), ('cakaudrove', 'Cakaudrove'), ('kadavu', 'Kadavu'), ('lau', 'Lau'), ('lomaiviti', 'Lomaiviti'), ('macuata', 'Macuata'), ('nadroga/navosa', 'Nadroga/Navosa'), ('naitasiri', 'Naitasiri'), ('namosi', 'Namosi'), ('ra', 'Ra'), ('rewa', 'Rewa'), ('serua', 'Serua'), ('tailevu', 'Tailevu')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='exam_name',
            field=models.CharField(choices=[('BED', 'BED Degree In Theology'), ('DIP', 'Diploma In Theology')], max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='fathers_name',
            field=models.CharField(help_text='Full name on Birth Certificate', max_length=100, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='mothers_name',
            field=models.CharField(help_text='Full name on Birth Certificate', max_length=100, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='admissionstudent',
            name='name',
            field=models.CharField(help_text='Full name on Birth Certificate', max_length=100, verbose_name='Full Name'),
        ),
    ]
